# Generated by Django 2.0 on 2019-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysub',
            name='image',
            field=models.FileField(null=True, upload_to='media/uploads'),
        ),
    ]
