# Generated by Django 2.0 on 2019-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mysub_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='media/uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='mysub',
            name='image',
        ),
    ]
