# Generated by Django 2.0 on 2019-11-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191106_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mysub',
        ),
    ]
