# Generated by Django 2.0 on 2019-11-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mysub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysub',
            old_name='owner',
            new_name='user',
        ),
    ]
