# Generated by Django 2.0 on 2019-11-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191107_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
